WebMDW/Controllers/ControlUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMDW.Controllers;
using WebMDW.Models;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;

namespace WebMDW.Controllers
{
    public class ControlUserController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        [Authorize]
        public ActionResult GetAllUsers()
        {
           var AllUsers = _context.Users.ToList();

           return View(AllUsers);
        }

        [Authorize]
        public ActionResult SetRoleUser()
        {
            RoleViewModel roles = new RoleViewModel
            {
                Users = _context.Users.ToList(),
                Role = _context.Roles.ToList()
            };

            return View(roles);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SetRole(string UserId, string RoleId)
        {
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_context));

            var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(_context));

            if (UserId != null && RoleId != null)
            {
                var user = _context.Users.FirstOrDefault(a => a.Id == UserId);
                var role = _context.Roles.FirstOrDefault(a => a.Id == RoleId);

                userManager.AddToRole(user.Id, role.Name);
            }

            return RedirectToAction("SetRoleUser");
        }
    }
}

WebMDW/Views/ControlUser/GetAllUsers.cshtml
@model IEnumerable<WebMDW.Models.ApplicationUser>

<h2>Все пользователи</h2>

<div class="row">
    <div class="col-md-10">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Пользователь</th>
                    <th scope="col">Роль</th>
                    <th scope="col">Проект</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var user in Model)
                {
                <tr>
                    <td>@user.UserName</td>
                    <td>@user.Roles.Select(a => a.UserId == user.Id).Aggregate((i,j) => i)</td>
                    <td>Project</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
  </div>

WebMDW/Views/ControlUser/SetRoleUser.cshtml
@model WebMDW.Models.RoleViewModel
<h2>Назначение роли</h2>

<div class="row">
    <div class="col-md-8">
      
            @using (Html.BeginForm("SetRole", "ControlUser", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="col-md-5 control-label">Роль</label>
                    <div class="col-md-6">
                        <select class="form-control" name="RoleId">
                            @foreach (var role in Model.Role)
                            {
                                <option value="@role.Id">@role.Name</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-5">Пользователь</label>
                    <div class="col-md-6">
                        <select class="form-control" name="UserId">
                            @foreach (var user in Model.Users)
                            {
                                <option value="@user.Id">@user.UserName</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Добавить" class="btn btn-default" />
                    </div>
                </div>

            }
       
    </div>

</div>