WebMDW/Controllers/PriorityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMDW.Models.Priority;
using WebMDW.Models;
using System.Threading.Tasks;

namespace WebMDW.Controllers
{
    public class PriorityController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        [Authorize]
        public ActionResult AddPriority()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> CreateNewPriority(PriorityModel model)
        {
            if (model.Name != null)
            {
                PriorityModel priority = new PriorityModel
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name
                };

                _context.Priorirtys.Add(priority);
                _context.SaveChanges();
            }

            return RedirectToAction("AddPriority");
        }

        [Authorize]
        public PriorityModel GetPriority(Guid Id)
        {
            var SelectPriorityFromDb = _context.Priorirtys.FirstOrDefault(a => a.Id == Id);

            return SelectPriorityFromDb;
        }
    }
}

WebMDW/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using Microsoft.AspNet.Identity.EntityFramework;
using WebMDW.Models;

namespace WebMDW.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Role
        [Authorize]
        public ActionResult AddRole()
        {
            return View();
        }

        [Authorize]
        public ActionResult GetAllRoles()
        {
            return View(_context.Roles.ToList());
        }        

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> CreateNewRole(string NameRole)
        {
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(_context));

            if (NameRole != string.Empty && NameRole != null)
            {
                var role = new IdentityRole {Name = NameRole };

                roleManager.Create(role);
            }

            return RedirectToAction("AddRole");
        }
    }
}

WebMDW/Controllers/StageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebMDW.Models;
using WebMDW.Models.Stage;

namespace WebMDW.Controllers
{
    public class StageController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

       // GET: Stage
       [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateNewStage(StageModel model)
        {
            if (ModelState.IsValid)
            {
                StageModel st = new StageModel
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name
                };

                _context.Stages.Add(st);
                _context.SaveChanges();
            }

            return View("Index");
        }

        [Authorize]
        public ActionResult Update(Guid Id)
        {
            ViewBag.ProjectId = Id;

            return View(_context.Stages.ToList());
        }

        [HttpPost]
        [Authorize]
        public RedirectToRouteResult UpdateStageProject(Guid Id, Guid ProjectId)
        {
            var _stage = _context.Stages.FirstOrDefault(a => a.Id == Id);

            var _project = _context.Projects.FirstOrDefault(t => t.Id == ProjectId);

            _project.Stages = _stage;

            _context.SaveChanges();

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }
    }
}

WebMDW/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMDW.Models.Status;
using WebMDW.Models;
using System.Threading.Tasks;

namespace WebMDW.Controllers
{
    public class StatusController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Status
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> CreateNewStatus(StatusModel model)
        {

            if (ModelState.IsValid)
            {
                StatusModel status = new StatusModel
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name
                };

                _context.Status.Add(status);

                _context.SaveChanges();
            }

            return View("Index");
        }

        [Authorize]
        public StatusModel GetStatus(string Name)
        {
            var _status = _context.Status.FirstOrDefault(a => a.Name == Name);

            return _status;
        }

        [Authorize]
        public ActionResult Update(Guid Id)
        {
            ViewBag.ProjectId = Id;

            return View(_context.Status.ToList());
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> UpdateStatusProject(Guid Id, Guid ProjectId)
        {
            var _project = _context.Projects.FirstOrDefault(a => a.Id == ProjectId);

            var _status = _context.Status.FirstOrDefault(t => t.Id == Id);

            _project.Status = _status;

            _context.SaveChanges();

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }
    }
}

WebMDW/Views/Shared/_AdminMenu.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Проекты</a>
    <div class="dropdown-menu" aria-labelledby="dropdown03">
        @Html.ActionLink("Добавление", "AddProject", "Project", null, new { @class = "dropdown-item" })
        @Html.ActionLink("Список всех проектов", "GetAllProject", "Project", null, new { @class = "dropdown-item" })
    </div>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Пользователи</a>
    <div class="dropdown-menu" aria-labelledby="dropdown03">
        @Html.ActionLink("Добавление", "Register", "Account", null, new { @class = "dropdown-item" })
        @Html.ActionLink("Список всех пользователей", "GetAllUsers", "ControlUser", null, new { @class = "dropdown-item" })
        @Html.ActionLink("Назначение роли", "SetRoleUser", "ControlUser", null, new { @class = "dropdown-item" })
    </div>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Роли</a>
    <div class="dropdown-menu" aria-labelledby="dropdown03">
        @Html.ActionLink("Добавление новой роли", "AddRole", "Role", null, new { @class = "dropdown-item" })
        @Html.ActionLink("Список всех ролей", "GetAllRoles", "Role", null, new { @class = "dropdown-item" })
    </div>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Статусы</a>
    <div class="dropdown-menu" aria-labelledby="dropdown03">
        @Html.ActionLink("Добавление статуса", "Index", "Status", null, new { @class = "dropdown-item" })
    </div>
</li>

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Этапы проекта</a>
    <div class="dropdown-menu" aria-labelledby="dropdown03">
        @Html.ActionLink("Добавление этапа", "Index", "Stage", null, new { @class = "dropdown-item" })

    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="dropdown03" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Приоритеты</a>
    <div class="dropdown-menu" aria-labelledby="dropdown03">
        @Html.ActionLink("Добавление приоритета", "AddPriority", "Priority", null, new { @class = "dropdown-item" })

    </div>
</li>

WebMDW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – ManagerDW</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
        <a class="navbar-brand" href="#">ManagerDW</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

       @if (User.Identity.IsAuthenticated)
       {
        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mr-auto">
                

                @if (User.IsInRole("AdminMDW"))
                {
                    @Html.Partial("_AdminMenu")
                }
                else
                {
                    @Html.Partial("_UserMenu")
                }
            </ul>
            <span class="navbar-text">
                @Html.Partial("_LoginPartial")
            </span>
        </div>
       }
    </div>
    </nav>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                        <li>@Html.ActionLink("О программе", "About", "Home")</li>
                        <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>*@
    <div class="container" style="margin-top:20px">
        @RenderBody()
      
        </div>
    
        <footer class="footer">
            <div class="container">
                <span class="text-muted">@DateTime.Now.Year - Разработано в dwsoft.org</span>
            </div>
        </footer>
   
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

WebMDW/Views/Shared/_UserMenu.cshtml
<li class="nav-item active">
    @Html.ActionLink("Мои проекты","MyProjects", "Project", null, new { @class="nav-link"})
</li>