WebMDW/Models/Project/ProjectModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using WebMDW.Models;
using WebMDW.Models.Stage;
using WebMDW.Models.Status;
using System.ComponentModel.DataAnnotations;

namespace WebMDW.Models.Project
{
    public class ProjectModel
    {
        public Guid Id { get; set; }

        [Required]
        [Display(Name = "Название проекта")]
        public string Name { get; set; }

        [Display(Name = "Цена проекта")]
        public int Price { get; set; }
        
        [Required]
        [Display(Name = "Дата начала проекта")]
        public DateTime? DateBegin { get; set; }

        [Display(Name = "Дата завершения проекта")]
        public DateTime? DateEnd { get; set; }

        [Display(Name = "Ссылка на проект")]
        public string UrlProjectDemo { get; set; }

        [Display(Name = "Процент завершенности проекта")]
        public int ProcentComplete { get; set; }

        [Display(Name = "Этап проекта")]
        public virtual StageModel Stages { get; set; }

        [Display(Name = "Статус проекта")]
        public virtual StatusModel Status { get; set; }

        public virtual ICollection<ApplicationUser> User { get; set; }

        public virtual ICollection<Task.TaskModel> Tasks { get; set; }

    }
}

WebMDW/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMDW.Models;
using WebMDW.Models.Stage;
using WebMDW.Models.Project;
using WebMDW.Models.Status;
using System.Data.Entity;
using System.Threading.Tasks;

namespace WebMDW.Controllers
{
    public class ProjectController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        [Authorize]
        public ActionResult MyProjects()
        {
            var SelectProjectUser = _context.Projects.Include(t => t.User).ToList();

            return View(SelectProjectUser);
        }

        [Authorize]
        public ActionResult AddUserInProject(Guid Id)
        {
            ViewBag.ProjectId = Id;

            return View(_context.Users.ToList());
        }

        [Authorize]
        public ActionResult AddProject()
        {
            return View();
        }

        [Authorize]
        public ActionResult GetAllProject()
        {
            var Projects = _context.Projects.ToList();

            return View(Projects);
        }


        [Authorize]
        public ActionResult SelectProject(Guid Id)
        {
            var GetProject = _context.Projects.FirstOrDefault(a => a.Id == Id);

            return View(GetProject);
        }

        [Authorize]
        public StageModel GetStage(string NameStage)
        {
            var SelectStage = _context.Stages.FirstOrDefault(a => a.Name == NameStage);

            return SelectStage;
        }

        [Authorize]
        public StatusModel GetStatus(string NameStatus)
        {
            var SelectStatus = _context.Status.FirstOrDefault(a => a.Name == NameStatus);

            return SelectStatus;
        }

        [Authorize]
        public ProjectModel GetProject(Guid Id)
        {
            return _context.Projects.FirstOrDefault(a => a.Id == Id);
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> SaveUserInProject(Guid ProjectId, List<ApplicationUser> UsersId)
        {
            var _project = _context.Projects.FirstOrDefault(a => a.Id == ProjectId);

            foreach (var user in UsersId)
            {
                var _selectUser = _context.Users.FirstOrDefault(a => a.Id == user.Id);

                _project.User.Add(_selectUser);
                _context.SaveChanges();
            };

            return RedirectToAction("AddUserInProject", new { id = _project.Id });
        }

        [HttpPost]
        [Authorize]
        public RedirectToRouteResult CreateNewProject(ProjectModel model)
        { 
            var stage = GetStage("Анализ требований");
            var status = GetStatus("В работе");
            var user = _context.Users.FirstOrDefault(a => a.UserName == User.Identity.Name);
            var nameProject = model.Name;
            var urlDemoPRoject = model.UrlProjectDemo;

            ProjectModel project = new ProjectModel
                {
                    Id = Guid.NewGuid(),
                    Name = nameProject,
                    ProcentComplete = 0,
                    Price = model.Price,
                    DateBegin = DateTime.Now,
                    DateEnd = null,
                    UrlProjectDemo = urlDemoPRoject,
                    Stages = stage,
                    Status = status,
                    User = new List<ApplicationUser>() { user },
                  
                };

             _context.Projects.Add(project);
             _context.SaveChanges();

            return RedirectToAction("GetAllProject");
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Delete(Guid ProjectId)
        {
            var project = GetProject(ProjectId);

            _context.Projects.Remove(project);
            _context.SaveChanges();

            return RedirectToAction("GetAllProject", "Project");
        }

        [Authorize]
        public ActionResult UpdateProcent(Guid Id)
        {
            ViewBag.ProjectId = Id;
            return View();
        }

        [HttpPost]
        [Authorize]
        public RedirectToRouteResult UpdateProcentProject(Guid ProjectId, int Procent)
        {
            var _project = GetProject(ProjectId);

            _project.ProcentComplete = Procent;

            _context.SaveChanges();

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }

    }
}

WebMDW/Controllers/StageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebMDW.Models;
using WebMDW.Models.Stage;

namespace WebMDW.Controllers
{
    public class StageController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

       // GET: Stage
       [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateNewStage(StageModel model)
        {
            if (ModelState.IsValid)
            {
                StageModel st = new StageModel
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name
                };

                _context.Stages.Add(st);
                _context.SaveChanges();
            }

            return View("Index");
        }

        [Authorize]
        public ActionResult Update(Guid Id)
        {
            ViewBag.ProjectId = Id;

            return View(_context.Stages.ToList());
        }

        [HttpPost]
        [Authorize]
        public RedirectToRouteResult UpdateStageProject(Guid Id, Guid ProjectId)
        {
            var _stage = _context.Stages.FirstOrDefault(a => a.Id == Id);

            var _project = _context.Projects.FirstOrDefault(t => t.Id == ProjectId);

            _project.Stages = _stage;

            _context.SaveChanges();

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }
    }
}

WebMDW/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMDW.Models.Status;
using WebMDW.Models;
using System.Threading.Tasks;

namespace WebMDW.Controllers
{
    public class StatusController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Status
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> CreateNewStatus(StatusModel model)
        {

            if (ModelState.IsValid)
            {
                StatusModel status = new StatusModel
                {
                    Id = Guid.NewGuid(),
                    Name = model.Name
                };

                _context.Status.Add(status);

                _context.SaveChanges();
            }

            return View("Index");
        }

        [Authorize]
        public StatusModel GetStatus(string Name)
        {
            var _status = _context.Status.FirstOrDefault(a => a.Name == Name);

            return _status;
        }

        [Authorize]
        public ActionResult Update(Guid Id)
        {
            ViewBag.ProjectId = Id;

            return View(_context.Status.ToList());
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> UpdateStatusProject(Guid Id, Guid ProjectId)
        {
            var _project = _context.Projects.FirstOrDefault(a => a.Id == ProjectId);

            var _status = _context.Status.FirstOrDefault(t => t.Id == Id);

            _project.Status = _status;

            _context.SaveChanges();

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }
    }
}

WebMDW/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMDW.Models;
using WebMDW.Models.Task;
using WebMDW.Models.Priority;
using WebMDW.Models.Status;
using System.Data.Entity;
using System.Threading.Tasks;
using WebMDW.Controllers;

namespace WebMDW.Controllers
{
    public class TaskController : Controller
    {
        ApplicationDbContext _context = new ApplicationDbContext();

        [Authorize]
        public ActionResult AddTask(Guid Id)
        {
            ViewBag.ProjectId = Id;

            TaskViewModel task = new TaskViewModel
            {
                Prioritys = _context.Priorirtys.ToList()
            };

            return View(task);
        }

        [Authorize]
        public PriorityModel GetPriority(Guid Id)
        {
            var SelectPriorityFromDb = _context.Priorirtys.FirstOrDefault(a => a.Id == Id);

            return SelectPriorityFromDb;
        }


        [HttpPost]
        [Authorize]
        public async Task<ActionResult> CreateNewTask(Guid PriorId, string NameTask, Guid ProjectId)
        {
            if (NameTask != null && PriorId != null && ProjectId != null)
            {
                var project = _context.Projects.FirstOrDefault(a => a.Id == ProjectId);
                var prior = GetPriority(PriorId);
                var status = GetStatus("В работе");

                TaskModel task = new TaskModel
                {
                   Id = Guid.NewGuid(),
                   Name = NameTask,
                   DateBegin = DateTime.Now,
                   Priority = prior,
                   Projects = new List<Models.Project.ProjectModel>() { project},
                   Status = status
                };

                _context.Tasks.Add(task);
                _context.SaveChanges();
            }

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }

        [Authorize]
        public StatusModel GetStatus(string Name)
        {
            var _status = _context.Status.FirstOrDefault(a => a.Name == Name);

            return _status;
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> UpdateStatus(Guid Id, Guid ProjectId)
        {
            var _task = GetTask(Id);

            var _status = GetStatus("Завершен");

            _task.Status = _status;

            _task.DateEnd = DateTime.Now;

            _context.SaveChanges();

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }

        [Authorize]
        public TaskModel GetTask(Guid Id)
        {
            var _task = _context.Tasks.FirstOrDefault(a => a.Id == Id);

            return _task;
        }

        [HttpGet]
        [Authorize]
        public RedirectToRouteResult Delete(Guid Id, Guid ProjectId)
        {
            var _task = _context.Tasks.FirstOrDefault(a => a.Id == Id);

            if (_task != null)
            {
                _context.Tasks.Remove(_task);
                _context.SaveChanges();
            }

            return RedirectToAction("SelectProject", "Project", new { id = ProjectId});
        }
    }
}

WebMDW/Views/Project/AddProject.cshtml
@model WebMDW.Models.Project.ProjectModel

<h2>Добавление нового проекта</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("CreateNewProject", "Project", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-md-5 control-label" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Price, new { @class = "col-md-5 control-label" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.UrlProjectDemo, new { @class = "col-md-5 control-label" })
            <div class="col-md-6">
                @Html.TextBoxFor(m => m.UrlProjectDemo, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.UrlProjectDemo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>

}
        </section>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMDW/Views/Project/AddUserInProject.cshtml
@using WebMDW.Models.Project
@using WebMDW.Models
@model IEnumerable<ApplicationUser>

<h2>Добавление пользователей в проект</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("SaveUserInProject", "Project", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="form-group">
                    <label class="control-label col-md-5">Пользователи</label>
                    <div class="col-md-6">
                        <select class="form-control col-md-5" name="UsersId">
                       @foreach (var user in Model)
                       {
                           <option value="@user.Id">@user.UserName</option>
                       }
                       </select>  
                        <input type="hidden" value="@ViewBag.ProjectId" name="ProjectId"/>
                    </div>
                </div>

                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Добавить" class="btn btn-default" />
                    </div>
                </div>

            }
        </section>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMDW/Views/Project/GetAllProject.cshtml
@model IEnumerable<WebMDW.Models.Project.ProjectModel>

<h2>Все проекта</h2>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">Название проекта</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Этап</th>
                    <th scope="col">Действие</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var project in Model)
                {
                <tr>                    
                    <td>@project.Name</td>
                    <td>
                        @if (project.Status.Name == "В работе")
                        {
                            <span class="badge badge-pill badge-info">@project.Status.Name</span>
                        }
                        else if(project.Status.Name == "Завершен")
                        {
                            <span class="badge badge-pill badge-success">@project.Status.Name</span>
                        }
                        else
                        {
                            <span class="badge badge-pill badge-danger">@project.Status.Name</span>
                        }
                    </td>
                    <td>
                        <span class="badge badge-pill badge-dark">@project.Stages.Name</span> 
                    </td>

                    <td>
                        @Html.ActionLink("Выбрать", "SelectProject", "Project", new { id = project.Id }, new { @class = "btn btn-outline-primary btn-sm" })
                        @Html.ActionLink("Удалить", "Delete", "Project", new { projectid = project.Id }, new { @class = "btn btn-outline-danger btn-sm" })

                    </td>
                </tr>
                }

            </tbody>
        </table>
    </div>

</div>

WebMDW/Views/Project/MyProjects.cshtml
@model IEnumerable<WebMDW.Models.Project.ProjectModel>
@{ 
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}
<h2>Мои проекты</h2>

<div class="row">
    @foreach (var myproject in Model)
    {
        <div class="col-md-4">

            <div class="card">
                <div class="card-header">
                    @myproject.Name
                </div>
                <div class="card-body">
                    <p class="card-text">Этап: @myproject.Stages.Name</p>
                    <p class="card-text">Статус: @myproject.Status.Name</p>
                    <p class="card-text">Заверешн на: @myproject.ProcentComplete</p>
                    @Html.ActionLink("Посмотреть", "SelectProject", "Project", new { id = myproject.Id }, new { @class = "btn btn-primary" })
                </div>
            </div>
            
        </div>
    }
    </div>

WebMDW/Views/Project/SelectProject.cshtml
@using WebMDW.Models.Task
@model WebMDW.Models.Project.ProjectModel
@{ 
    Layout = "~/Views/Shared/_LayoutMenu.cshtml";
}
<div class="row">
    <div class="col-md-12">

        @if (User.IsInRole("AdminMDW"))
        {
        <div class="btn-group" role="group" aria-label="Basic example">
            @Html.ActionLink("Добавление задачи", "AddTask", "Task", new { id = Model.Id }, new { @class = "btn btn-warning btn-sm" })
            @Html.ActionLink("Изменить статус", "Update", "Status", new { id = Model.Id }, new { @class = "btn btn-warning btn-sm" })
            @Html.ActionLink("Изменить этап", "Update", "Stage", new { id = Model.Id }, new { @class = "btn btn-warning btn-sm" })
            @Html.ActionLink("Изменить % завершения", "UpdateProcent", "Project", new { id = Model.Id }, new { @class = "btn btn-warning btn-sm" })
            @Html.ActionLink("Добавление пользователей", "AddUserInProject", "Project", new { id = Model.Id }, new { @class = "btn btn-warning btn-sm" })
        </div>
           
        }

        <h5 class="display-5">@Model.Name</h5>
        Этап: <span class="badge badge-pill badge-dark">@Model.Stages.Name</span><br />
        Статус:
          @if (Model.Status.Name == "В работе")
                        {
                            <span class="badge badge-pill badge-info">@Model.Status.Name</span>
                        }
                        else if(Model.Status.Name == "Завершен")
                        {
                            <span class="badge badge-pill badge-success">@Model.Status.Name</span>
                        }
                        else
                        {
                            <span class="badge badge-pill badge-danger">@Model.Status.Name</span>
                        }
        <br />
        Цена проекта: <span class="badge badge-pill badge-dark">@Model.Price рублей</span><br />
        Проверка результата: <a href="@Model.UrlProjectDemo">@Model.UrlProjectDemo</a>
        <span>Контактные лица</span>
        @foreach(var contact in Model.User)
        {
            <span class="text-primary">@contact.Email</span>
        }
        <br /><br />

        <span>Проект завершен:</span>
        <div class="progress">
            <div class="progress-bar" role="progressbar" style="width:@Model.ProcentComplete%"
                 aria-valuenow="@Model.ProcentComplete" aria-valuemin="0" aria-valuemax="100"></div>
        </div>

    </div>

    <div class="col-md-12" style="margin-top:20px;">
     <h5>Задачи проекта</h5>
     <br />

     <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
         <li class="nav-item">
             <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">В работе</a>
         </li>
         <li class="nav-item">
             <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Завершены</a>
         </li>
     </ul>
    </div>
</div>

    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
            <div class="row">
            
            @foreach (var task in Model.Tasks.OrderByDescending(a => a.Priority.Name == "Высокий" && a.Status.Name == "В работе"))
            {
            <div class="col-md-3" style="margin-top:20px;">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">@task.Name</h5>
                        <p class="text-dark">
                            Приоритет:

                        @if (task.Priority.Name == "Высокий")
                        {
                             <span class="badge badge-pill badge-danger">@task.Priority.Name</span>
                        }
                        else if (task.Priority.Name == "Средний")
                        {
                            <span class="badge badge-pill badge-warning">@task.Priority.Name</span>
                        }
                        else
                        {
                             <span class="badge badge-pill badge-info">@task.Priority.Name</span>
                        }
                        </p>

                    @if (User.IsInRole("AdminMDW"))
                    {

                    @Html.ActionLink("Завершить", "UpdateStatus", "Task", new { id = task.Id, projectid = Model.Id }, new { @class = "btn btn-outline-success btn-sm" })

                    @Html.ActionLink("Удалить", "Delete", "Task", new { id = task.Id, projectid = Model.Id }, new { @class = "btn btn-outline-danger btn-sm" })
                
                    }
                    </div>
                </div>
            </div>
            }
        </div>
        </div>
     
    </div>

WebMDW/Views/Project/UpdateProcent.cshtml
@model WebMDW.Models.Project.ProjectModel

<h2>Изменение процента завершенности</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("UpdateProcentProject", "Project", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-5">Процент завершенности</label>
                    <div class="col-md-6">
                        <input type="text" name="Procent" class="form-control" />
                        <input type="hidden" name="ProjectId" value="@ViewBag.ProjectId" />
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Изменить" class="btn btn-outline-primary btn-sm" />
                    </div>
                </div>

            }
        </section>
    </div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}